FROM nvidia/cuda:12.1.0-base-ubuntu22.04

RUN apt update && apt install -y git python3 python3-pip

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

RUN git clone https://github.com/THUDM/ChatGLM-6B

WORKDIR /app/ChatGLM-6B

RUN pip install -r requirements.txt

RUN sed -i "s/demo.queue().launch(share=False, inbrowser=True)/demo.queue(max_size=20).launch(server_name=\"0.0.0.0\")/g" /app/ChatGLM-6B/web_demo.py

ENTRYPOINT ["python3", "web_demo.py"]