FROM nvidia/cuda:12.1.0-base-ubuntu22.04

RUN apt update && apt install -y git python3 python3-pip

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

RUN git clone https://github.com/THUDM/ChatGLM-6B

WORKDIR /app/ChatGLM-6B

RUN pip install -r requirements.txt

RUN pip install -r fastapi uvicorn

ENTRYPOINT ["python3", "api.py"]